export const UPLOAD_IMAGE = 'app/KYCPage/UPLOAD_IMAGE';
export const UPLOAD_BANK_IMAGE = 'app/KYCPage/UPLOAD_BANK_IMAGE';
export const UPLOAD_PAN_IMAGE = 'app/KYCPage/UPLOAD_PAN_IMAGE';
export const SET_PAN_IMAGE = 'app/KYCPage/SET_PAN_IMAGE';
export const REMOVE_PAN_IMAGE = 'app/KYCPage/REMOVE_PAN_IMAGE';

export const SET_LOCAL_PAN = 'app/KYCPage/SET_LOCAL_PAN';
export const SET_REMOTE_PAN = 'app/KYCPage/SET_REMOTE_PAN';
export const EDIT_PAN = 'app/KYCPage/EDIT_PAN';
export const GET_USER_PAN = 'app/KYCPage/GET_USER_PAN';
export const REMOVE_PAN = 'app/KYCPage/REMOVE_PAN';

export const UPLOAD_SIGNATURE_IMAGE = 'app/KYCPage/UPLOAD_SIGNATURE_IMAGE';
export const SET_SIGNATURE_IMAGE = 'app/KYCPage/SET_SIGNATURE_IMAGE';
export const REMOVE_SIGNATURE_IMAGE = 'app/KYCPage/REMOVE_SIGNATURE_IMAGE';

export const SET_LOCAL_SIGNATURE = 'app/KYCPage/SET_LOCAL_SIGNATURE';
export const SET_REMOTE_SIGNATURE = 'app/KYCPage/SET_REMOTE_SIGNATURE';
export const EDIT_SIGNATURE = 'app/KYCPage/EDIT_SIGNATURE';

export const SET_ID = 'app/KYCPage/SET_ID';

export const SET_BANK_IMAGES = 'app/KYCPage/SET_BANK_IMAGES';
export const REMOVE_BANK_IMAGES = 'app/KYCPage/REMOVE_BANK_IMAGES';

export const SET_ADDRESS_IMAGES = 'app/KYCPage/SET_ADDRESS_IMAGES';
export const REMOVE_ADDRESS_IMAGES = 'app/KYCPage/REMOVE_BANK_IMAGES';

export const UPLOAD_ADDRESS_IMAGE = 'app/KYCPage/UPLOAD_ADDRESS_IMAGE';

export const SET_LOCAL_ADDRESS = 'app/KYCPage/SET_LOCAL_ADDRESS';
export const SET_REMOTE_ADDRESS = 'app/KYCPage/SET_REMOTE_ADDRESS';
export const GET_ADDRESS = 'app/KYCPage/GET_ADDRESS';
export const EDIT_ADDRESS = 'app/KYCPage/EDIT_ADDRESS';
export const REMOVE_ADDRESS = 'app/KYCPage/REMOVE_ADDRESS';

export const SET_LOCAL_BANK_DETAILS = 'app/KYCPage/SET_LOCAL_BANK_DETAILS';
export const GET_BANK_DETAILS = 'app/KYCPage/GET_BANK_DETAILS';

export const SET_REMOTE_BANK_DETAILS = 'app/KYCPage/SET_REMOTE_BANK_DETAILS';
export const EDIT_BANK_DETAILS = 'app/KYCPage/EDIT_BANK_DETAILS';
export const REMOVE_BANK_DETAILS = 'app/KYCPage/REMOVE_BANK_DETAILS';
export const SET_LOADING_STATE = 'app/KYCPage/SET_LOADING_STATE';
